<script>
 import{onMount}from'svelte';import{ShieldCheck,Check,X,Play,Undo2,Plus}from'lucide-svelte';
 let approvals=$state([]),rollbacks=$state([]),toolId=$state('create-app'),slug=$state(''),title=$state(''),path=$state(''),content=$state(''),message=$state(''),error=$state('');onMount(load);
 async function load(){const r=await fetch('/api/safety');const d=await r.json();approvals=d.approvals??[];rollbacks=d.rollbacks??[]}
 function input(){return toolId==='create-app'?{slug,title:title||slug,description:'A local application generated through the J.A.R.V.I.S. approval workflow'}:{path,content}}
 async function request(){error='';const r=await fetch('/api/safety',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation:'request',toolId,input:input(),reason:`Create ${toolId==='create-app'?'a local application':'a repository file'}`})});const d=await r.json();if(!r.ok){error=d.error;return}message='Approval requested';await load()}
 async function decide(id,decision){const r=await fetch('/api/safety',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation:'decide',id,decision})});const d=await r.json();if(!r.ok)error=d.error;await load()}
 async function execute(item){const r=await fetch('/api/tools',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:item.toolId,input:item.input,approvalId:item.id})});const d=await r.json();if(!r.ok){error=d.error;return}message=`Executed ${item.toolId}. Rollback is available.`;await load()}
 async function rollback(id){const r=await fetch('/api/safety',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({operation:'rollback',id})});const d=await r.json();if(!r.ok){error=d.error;return}message='Changes rolled back';await load()}
</script>
<svelte:head><title>Safety · J.A.R.V.I.S.</title></svelte:head><div class="page"><header><ShieldCheck size={22}/><div><h1>Safety & Approvals</h1><p>Review exact inputs before any repository mutation. Approvals are single-use.</p></div></header><section class="request"><h2>Request a controlled action</h2><select bind:value={toolId}><option value="create-app">Generate local Svelte app</option><option value="write-file">Write new repository file</option></select>{#if toolId==='create-app'}<input bind:value={slug} placeholder="app-slug"/><input bind:value={title} placeholder="Application title"/>{:else}<input bind:value={path} placeholder="relative/path.txt"/><textarea bind:value={content} placeholder="File content"></textarea>{/if}<button onclick={request} disabled={toolId==='create-app'?!slug:!path}><Plus size={14}/>Request approval</button></section>{#if error}<p class="error">{error}</p>{/if}{#if message}<p class="success">{message}</p>{/if}<section><h2>Approval queue</h2><div class="list">{#each approvals as item(item.id)}<article><div><strong>{item.toolId}</strong><span>{item.reason}</span><pre>{JSON.stringify(item.input,null,2)}</pre></div><b class={item.status}>{item.status}</b>{#if item.status==='pending'}<button onclick={()=>decide(item.id,'approved')} aria-label="Approve"><Check size={15}/></button><button onclick={()=>decide(item.id,'denied')} aria-label="Deny"><X size={15}/></button>{:else if item.status==='approved'}<button onclick={()=>execute(item)}><Play size={14}/>Execute</button>{/if}</article>{/each}{#if approvals.length===0}<p>No approval requests.</p>{/if}</div></section><section><h2>Rollback journal</h2><div class="list">{#each rollbacks as item(item.id)}<article><div><strong>{item.toolId}</strong><span>{item.files.length} file change(s) · {new Date(item.createdAt).toLocaleString()}</span></div><b>{item.status}</b>{#if item.status==='available'}<button onclick={()=>rollback(item.id)}><Undo2 size={14}/>Rollback</button>{/if}</article>{/each}{#if rollbacks.length===0}<p>No rollback records.</p>{/if}</div></section></div>
<style>.page{padding:var(--space-6);display:grid;gap:var(--space-5);max-width:1100px}header{display:flex;gap:.8rem;align-items:center}h1{font-size:var(--text-2xl);margin:0}header p,.list p{color:var(--text-secondary);font-size:var(--text-sm);margin:.25rem 0}h2{font-size:var(--text-sm);margin:0 0 .7rem}.request{display:grid;grid-template-columns:1fr 1fr;gap:.6rem;border:1px solid var(--surface-border);background:var(--surface-card);border-radius:var(--radius-lg);padding:1rem}.request h2,.request textarea{grid-column:1/-1}input,select,textarea,button{border:1px solid var(--surface-border);background:var(--surface-card);color:var(--text-primary);border-radius:var(--radius-md);padding:.65rem}.request button,article button{display:flex;align-items:center;justify-content:center;gap:.35rem;cursor:pointer}.list{display:grid;gap:.6rem}article{display:flex;align-items:center;gap:.6rem;border:1px solid var(--surface-border);background:var(--surface-card);border-radius:var(--radius-lg);padding:.8rem}article>div{flex:1;min-width:0}article span{display:block;color:var(--text-secondary);font-size:var(--text-xs);margin-top:.25rem}pre{white-space:pre-wrap;font-size:var(--text-xs);max-height:120px;overflow:auto}article b{font-size:10px;text-transform:uppercase;color:var(--text-tertiary)}article b.approved{color:var(--color-success-500)}article b.denied{color:var(--color-error-500)}.error{color:var(--color-error-500)}.success{color:var(--color-success-500)}@media(max-width:640px){.page{padding:var(--space-4)}.request{grid-template-columns:1fr}.request h2,.request textarea{grid-column:auto}article{align-items:flex-start;flex-wrap:wrap}}</style>
