<script>
  import { onMount } from 'svelte'; import { BookOpen, Plus, Sparkles } from 'lucide-svelte';
  let skills=$state([]),show=$state(false),id=$state(''),name=$state(''),description=$state(''),instructions=$state(''),error=$state('');
  onMount(load);async function load(){const r=await fetch('/api/skills');const d=await r.json();skills=d.skills??[];error=d.error??''}
  async function create(){const r=await fetch('/api/skills',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id,name,description,instructions})});const d=await r.json();if(!r.ok){error=d.error;return}id=name=description=instructions='';show=false;await load()}
</script>
<svelte:head><title>Skills · J.A.R.V.I.S.</title></svelte:head>
<div class="page"><header><div><h1>Skill Engine</h1><p>{skills.length} reusable capabilities discovered from disk.</p></div><button onclick={()=>show=!show}><Plus size={15}/>Create skill</button></header>
{#if show}<section class="creator"><input bind:value={id} placeholder="skill-id"/><input bind:value={name} placeholder="Skill name"/><input bind:value={description} placeholder="Purpose"/><textarea bind:value={instructions} placeholder="Operational instructions"></textarea><button onclick={create} disabled={!id||!name||!instructions}><Sparkles size={14}/>Write and register</button></section>{/if}{#if error}<p class="error">{error}</p>{/if}
<section class="grid">{#each skills as skill(skill.id)}<article><BookOpen size={17}/><div><h2>{skill.name}</h2><p>{skill.description}</p><code>{skill.path}</code></div>{#if skill.generated}<span>Generated</span>{/if}</article>{/each}</section></div>
<style>.page{padding:var(--space-6);display:grid;gap:var(--space-5)}header{display:flex;justify-content:space-between;gap:1rem;align-items:center}h1{margin:0;color:var(--text-primary);font-size:var(--text-2xl)}header p{margin:.3rem 0;color:var(--text-secondary);font-size:var(--text-sm)}button,input,textarea{border:1px solid var(--surface-border);background:var(--surface-card);color:var(--text-primary);border-radius:var(--radius-md)}header button,.creator button{display:flex;align-items:center;gap:.4rem;padding:.65rem .9rem;cursor:pointer}.creator{display:grid;grid-template-columns:1fr 1fr;gap:.6rem}.creator input,.creator textarea{padding:.7rem}.creator textarea{grid-column:1/-1;min-height:110px}.creator button{justify-content:center;background:var(--color-neutral-900);color:white}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:.7rem}article{display:flex;gap:.7rem;padding:1rem;border:1px solid var(--surface-border);background:var(--surface-card);border-radius:var(--radius-lg)}article div{flex:1;min-width:0}h2{font-size:var(--text-sm);margin:0;color:var(--text-primary)}article p,code{font-size:var(--text-xs);color:var(--text-secondary)}code{display:block;overflow:hidden;text-overflow:ellipsis}article span{font-size:10px;color:var(--color-success-500)}.error{color:var(--color-error-500)}@media(max-width:640px){.page{padding:var(--space-4)}header{align-items:flex-start;flex-direction:column}.creator{grid-template-columns:1fr}.creator textarea{grid-column:auto}}</style>
