<script>
 import {onMount} from 'svelte';import{Bot,Play,Plus,Power,Trash2}from'lucide-svelte';
 let items=$state([]),name=$state(''),action=$state('task:'),schedule=$state('daily'),error=$state(''),message=$state('');onMount(load);
 async function load(){const r=await fetch('/api/workspace?kind=automations');const d=await r.json();items=d.items??[];error=d.error??''}
 async function create(){const r=await fetch('/api/workspace?kind=automations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,action,schedule,enabled:true})});const d=await r.json();if(!r.ok){error=d.error;return}name='';action='task:';await load()}
 async function patch(item,body){await fetch(`/api/workspace?kind=automations&id=${item.id}`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});await load()}
 async function run(item){const r=await fetch('/api/automations/run',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:item.id})});const d=await r.json();if(!r.ok){error=d.error;return}message=`${item.name} ran successfully`;await load()}
 async function remove(id){await fetch(`/api/workspace?kind=automations&id=${id}`,{method:'DELETE'});await load()}
</script>
<svelte:head><title>Automations · J.A.R.V.I.S.</title></svelte:head><div class="page"><header><Bot size={21}/><div><h1>Automations</h1><p>Restart-safe background actions. Runs are recorded in the audit log.</p></div></header><section class="form"><input bind:value={name} placeholder="Automation name"/><input bind:value={action} placeholder="task:Review inbox, note:Daily log, or notify:Message"/><input bind:value={schedule} placeholder="daily, hourly, or every N minutes"/><button onclick={create} disabled={!name||!action}><Plus size={14}/>Add</button></section>{#if error}<p class="error">{error}</p>{/if}{#if message}<p class="success">{message}</p>{/if}<section class="list">{#each items as item(item.id)}<article><button class:enabled={item.enabled} onclick={()=>patch(item,{enabled:!item.enabled})} aria-label="Toggle automation"><Power size={15}/></button><div><h2>{item.name}</h2><code>{item.action}</code><small>{item.schedule}{item.nextRunAt?` · Next ${new Date(item.nextRunAt).toLocaleString()}`:''}{item.lastRunAt?` · Last ${new Date(item.lastRunAt).toLocaleString()}`:''}</small></div><button onclick={()=>run(item)} disabled={!item.enabled} aria-label="Run"><Play size={15}/></button><button onclick={()=>remove(item.id)} aria-label="Delete"><Trash2 size={15}/></button></article>{/each}{#if items.length===0}<p>No automations yet.</p>{/if}</section></div>
<style>.page{padding:var(--space-6);display:grid;gap:var(--space-5);max-width:1100px}header{display:flex;align-items:center;gap:.8rem}h1{margin:0;font-size:var(--text-2xl)}header p,.list p{margin:.25rem 0;color:var(--text-secondary);font-size:var(--text-sm)}.form{display:flex;gap:.5rem;flex-wrap:wrap}input,button{border:1px solid var(--surface-border);background:var(--surface-card);color:var(--text-primary);border-radius:var(--radius-md);padding:.65rem}input{flex:1;min-width:170px}.form button,article button{display:flex;align-items:center;gap:.3rem;cursor:pointer}.list{display:grid;gap:.6rem}article{display:flex;align-items:center;gap:.7rem;border:1px solid var(--surface-border);background:var(--surface-card);border-radius:var(--radius-lg);padding:.8rem}article div{flex:1}h2{font-size:var(--text-sm);margin:0}code,small{display:block;font-size:var(--text-xs);color:var(--text-secondary);margin-top:.25rem}article button.enabled{color:var(--color-success-500)}.error{color:var(--color-error-500)}.success{color:var(--color-success-500)}@media(max-width:640px){.page{padding:var(--space-4)}.form{flex-direction:column}}</style>
