import { readdir, readFile } from 'node:fs/promises';
import { resolve, relative, join } from 'node:path';
import { createEntity, record, transaction } from '../core/store.js';
import type { ToolManifest } from '../core/types.js';
import { applyChanges, consumeApproval, createRollback } from '../safety/runtime.js';
import { recordExecution } from '../evaluation/runtime.js';

const root = process.cwd();
export const builtinTools: ToolManifest[] = [
  { id: 'list-directory', name: 'List directory', description: 'List files inside the repository', category: 'file-operations', safetyLevel: 0 },
  { id: 'read-file', name: 'Read file', description: 'Read a UTF-8 file inside the repository', category: 'file-operations', safetyLevel: 0 },
  { id: 'summarize-project', name: 'Summarize project', description: 'Inspect repository structure and package metadata', category: 'coding', safetyLevel: 0 },
  { id: 'create-task', name: 'Create task', description: 'Add a task to the local workspace', category: 'productivity', safetyLevel: 1 },
  { id: 'create-note', name: 'Create note', description: 'Add a note to the local workspace', category: 'productivity', safetyLevel: 1 }
  ,{ id: 'write-file', name: 'Write new file', description: 'Create a new UTF-8 file inside the repository with one-time approval', category: 'file-operations', safetyLevel: 2 }
  ,{ id: 'create-app', name: 'Create local app', description: 'Generate a standalone Svelte application under generated-apps/', category: 'meta', safetyLevel: 2 }
];

function insideRepo(path = '.') {
  const target = resolve(root, path);
  if (target !== root && !target.startsWith(root + '\\') && !target.startsWith(root + '/')) throw new Error('Path escapes repository boundary');
  return target;
}

export async function listTools() { const data = await import('../core/store.js').then((m) => m.snapshot()); return [...builtinTools, ...data.generatedTools]; }

async function executeToolInternal(id: string, input: Record<string, unknown>, approvalId?: string) {
  const tool = (await listTools()).find((item) => item.id === id);
  if (!tool) throw new Error('Unknown tool');
  if (tool.safetyLevel >= 2) {
    if (!approvalId) throw new Error('This tool requires a one-time approval');
    await consumeApproval(approvalId, id, input);
  }
  let output: unknown;
  if (id === 'list-directory') output = await readdir(insideRepo(String(input.path ?? '.')), { withFileTypes: true }).then((items) => items.map((item) => ({ name: item.name, type: item.isDirectory() ? 'directory' : 'file' })));
  else if (id === 'read-file') output = await readFile(insideRepo(String(input.path ?? 'README.md')), 'utf8').then((text) => text.slice(0, 100_000));
  else if (id === 'summarize-project') {
    const pkg = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
    const src = await readdir(join(root, 'src'), { recursive: true });
    output = { name: pkg.name, scripts: pkg.scripts, dependencies: { ...pkg.dependencies, ...pkg.devDependencies }, sourceFiles: src.length, root: relative(root, root) || '.' };
  } else if (id === 'create-task') output = await createEntity('tasks', { title: String(input.title ?? 'Untitled task'), description: String(input.description ?? ''), status: 'todo', priority: input.priority ?? 'medium', dueAt: input.dueAt });
  else if (id === 'create-note') output = await createEntity('notes', { title: String(input.title ?? 'Untitled note'), content: String(input.content ?? ''), tags: input.tags ?? [] });
  else if (id === 'write-file') {
    const path = String(input.path ?? ''); const content = String(input.content ?? ''); insideRepo(path); if (!path) throw new Error('path is required');
    const changes = [{ path, content }]; const rollback = await createRollback(approvalId!, id, changes); await applyChanges(changes); output = { path, rollbackId: rollback.id };
  } else if (id === 'create-app') {
    const slug = String(input.slug ?? '').toLowerCase(); if (!/^[a-z0-9-]+$/.test(slug)) throw new Error('slug must use lowercase letters, numbers, and hyphens');
    const title = String(input.title ?? slug); const description = String(input.description ?? 'Generated by J.A.R.V.I.S.'); const base = `generated-apps/${slug}`;
    const changes = [
      { path: `${base}/package.json`, content: JSON.stringify({ name: slug, private: true, version: '0.1.0', type: 'module', scripts: { dev: 'vite', build: 'vite build' }, devDependencies: { '@sveltejs/vite-plugin-svelte': '^7.0.0', svelte: '^5.0.0', vite: '^8.0.0' } }, null, 2) + '\n' },
      { path: `${base}/index.html`, content: '<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>' + title.replaceAll('<','&lt;') + '</title></head><body><div id="app"></div><script type="module" src="/src.js"></script></body></html>\n' },
      { path: `${base}/src.js`, content: "import { mount } from 'svelte';\nimport App from './App.svelte';\nmount(App, { target: document.getElementById('app') });\n" },
      { path: `${base}/App.svelte`, content: `<script>let count = $state(0);<\/script>\n<svelte:head><title>${title}</title></svelte:head>\n<main><p>Generated by J.A.R.V.I.S.</p><h1>${title}</h1><p>${description}</p><button onclick={() => count++}>Interactions: {count}</button></main>\n<style>:global(*){box-sizing:border-box}:global(body){margin:0;font-family:Inter,system-ui;background:#0b0d10;color:#e8eaed}main{max-width:720px;margin:12vh auto;padding:3rem;border:1px solid #2b3038;border-radius:18px;background:#12151a}p{color:#aeb4bd}button{padding:.7rem 1rem;border:1px solid #404650;border-radius:8px;background:#e8eaed;color:#111;cursor:pointer}</style>\n` },
      { path: `${base}/vite.config.js`, content: "import { defineConfig } from 'vite';\nimport { svelte } from '@sveltejs/vite-plugin-svelte';\nexport default defineConfig({ plugins: [svelte()] });\n" },
      { path: `${base}/README.md`, content: `# ${title}\n\n${description}\n\nRun with \`npm install && npm run dev\`.\n` }
    ];
    changes.forEach((change) => insideRepo(change.path)); const rollback = await createRollback(approvalId!, id, changes); await applyChanges(changes); output = { directory: base, files: changes.map((change) => change.path), rollbackId: rollback.id };
  } else output = { accepted: true, input, message: 'Generated declarative tool invoked' };
  await transaction((data) => record(data, { action: `tool:${id}`, entity: 'tool', outcome: 'success', detail: JSON.stringify(input).slice(0, 300) }));
  return output;
}

export async function executeTool(id: string, input: Record<string, unknown>, approvalId?: string) {
  const started = Date.now(); const startedAt = new Date().toISOString();
  try { const output = await executeToolInternal(id, input, approvalId); await recordExecution({ capability: id, kind: 'tool', startedAt, durationMs: Date.now() - started, ok: true }); return output; }
  catch (error) { await recordExecution({ capability: id, kind: 'tool', startedAt, durationMs: Date.now() - started, ok: false, error: error instanceof Error ? error.message : String(error) }); throw error; }
}

export async function registerTool(input: Omit<ToolManifest, 'generated'>) {
  if (!/^[a-z0-9-]+$/.test(input.id)) throw new Error('Tool id must use lowercase letters, numbers, and hyphens');
  if (input.safetyLevel < 0 || input.safetyLevel > 3) throw new Error('Invalid safety level');
  return transaction((data) => {
    if ([...builtinTools, ...data.generatedTools].some((tool) => tool.id === input.id)) throw new Error('Tool id already exists');
    const tool = { ...input, generated: true } as ToolManifest;
    data.generatedTools.push(tool);
    record(data, { action: 'register-tool', entity: 'tool', entityId: tool.id, outcome: 'success', detail: tool.description });
    return tool;
  });
}
